# Generated by Django 2.2 on 2019-05-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(default=-1.0, max_length=100),
            preserve_default=False,
        ),
    ]
